package study.ssm.studentmanagement.dao;

import study.ssm.studentmanagement.model.School;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    School selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    int updateByPrimaryKey(School record);
}