package study.ssm.studentmanagement.model;

import java.util.Date;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.created_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private String createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.created_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.updated_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private String updatedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.updated_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.deleted_flag
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    private Boolean deletedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.id
     *
     * @return the value of school.id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.id
     *
     * @param id the value for school.id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name
     *
     * @return the value of school.name
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name
     *
     * @param name the value for school.name
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.created_id
     *
     * @return the value of school.created_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public String getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.created_id
     *
     * @param createdId the value for school.created_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setCreatedId(String createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.created_time
     *
     * @return the value of school.created_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.created_time
     *
     * @param createdTime the value for school.created_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.updated_id
     *
     * @return the value of school.updated_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public String getUpdatedId() {
        return updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.updated_id
     *
     * @param updatedId the value for school.updated_id
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setUpdatedId(String updatedId) {
        this.updatedId = updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.updated_time
     *
     * @return the value of school.updated_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.updated_time
     *
     * @param updatedTime the value for school.updated_time
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.deleted_flag
     *
     * @return the value of school.deleted_flag
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public Boolean getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.deleted_flag
     *
     * @param deletedFlag the value for school.deleted_flag
     *
     * @mbg.generated Fri Nov 17 17:15:07 CST 2017
     */
    public void setDeletedFlag(Boolean deletedFlag) {
        this.deletedFlag = deletedFlag;
    }
}